# Generated by Django 5.1.3 on 2024-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_alter_slider_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=150)),
                ('about_desc', models.TextField()),
                ('about_img', models.ImageField(upload_to='')),
                ('about_subtitle', models.CharField(max_length=200)),
            ],
        ),
    ]
