# Generated by Django 5.1.3 on 2024-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_subtitle',
            new_name='about_head',
        ),
        migrations.AddField(
            model_name='about',
            name='about_subhead',
            field=models.TextField(default='Default subtitle'),
        ),
    ]
