# Generated by Django 5.1.3 on 2024-11-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_rename_about_subtitle_about_about_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
