# Generated by Django 5.1.3 on 2024-11-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Featured_Products',
            new_name='New_Arrival',
        ),
    ]
