# Generated by Django 5.1.3 on 2024-11-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0014_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
