# Generated by Django 5.1.3 on 2024-11-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0017_product_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
